language: python
python:
- '3.7'
install:
- pip install -r requirements.txt
- pip install -r requirements-dev.text
script:
- bandit -r .
- flake8 .
- pytest
# deploy:
#   provider: pypi
#   user:
#   on:
#     tags: true
#     distributions: sdist bdist_wheel
#     branch: master
#     repo: reponame
